plugins {
    id 'java'
    id 'xyz.jpenilla.run-paper' version '3.0.2'
    id 'net.ltgt.errorprone' version '5.1.0'
}

group = 'com.jhuanglululu'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = uri('https://repo.papermc.io/repository/maven-public/')
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.+'
    errorprone 'com.google.errorprone:error_prone_core:2.50.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:6.1.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.2'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Werror'
}

processResources {
    def props = [version: version]
    inputs.properties(props)
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

runServer {
    minecraftVersion '26.2'
}
